services:
  db:
    container_name: currency-exchange-db
    image: postgres:14-alpine
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "4679:5432"

  api:
    container_name: currency-exchange-api
    image: asalavei/currency-exchange-tomcat
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8181:8080"

  frontend:
    container_name: currency-exchange-frontend-nginx
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/:/usr/share/nginx/html