### Get all currencies - 200 OK
GET http://localhost:8080/api/currencies
Accept: application/json

### Create currency - 201 Created
POST http://localhost:8080/api/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=Pound Sterling &
code=GBP &
sign=£

### Create currency - 400 Bad Request
### Invalid or missing input data
POST http://localhost:8080/api/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name= &
code=GBP &
sign=£

### Create currency - 409 Conflict
### Currency already exists in the database
POST http://localhost:8080/api/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=Pound Sterling &
code=GBP &
sign=£

### Get currency by code - 200 OK
GET http://localhost:8080/api/currency/EUR
Accept: application/json

### Get currency by code - 400 Bad Request
### Invalid or missing input data
GET http://localhost:8080/api/currency/
Accept: application/json

### Get currency by code - 404 Not Found
### Currency not found in the database
GET http://localhost:8080/api/currency/CHF
Accept: application/json