### Get all exchange rate - 200 OK
GET http://localhost:8080/exchangeRates
Accept: application/json

### Get exchange rate by currency codes - 200 OK
GET http://localhost:8080/exchangeRate/USDGEL
Accept: application/json

### Get exchange rate by currency codes - 400 Bad Request
### Invalid or missing input data
GET http://localhost:8080/exchangeRate/USD
Accept: application/json

### Get exchange rate by currency codes - 404 Not Found
### Exchange rate not found in the database
GET http://localhost:8080/exchangeRate/GELEUR
Accept: application/json

### Create exchange rate - 201 Created
POST http://localhost:8080/exchangeRates
Accept: application/json
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=GEL &
targetCurrencyCode=BYN &
rate=1.212499

### Create exchange rate - 400 Bad Request
### Invalid or missing input data
POST http://localhost:8080/exchangeRates
Accept: application/json
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=GE &
targetCurrencyCode=BYN &
rate=1.212499

### Create exchange rate - 409 Conflict
#### Exchange rate already exists in the database
POST http://localhost:8080/exchangeRates
Accept: application/json
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=GEL &
targetCurrencyCode=BYN &
rate=1.212499

### Create exchange rate - 404 Not Found
#### Currency required to save the exchange rate not found
POST http://localhost:8080/exchangeRates
Accept: application/json
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=PHP &
targetCurrencyCode=BYN &
rate=1.212499

### Update exchange rate - 200 OK
PATCH http://localhost:8080/exchangeRate/USDRUB
Accept: application/json
Content-Type: application/x-www-form-urlencoded

rate=91.496732

### Update exchange rate - 400 Bad Request
### Invalid or missing input data
PATCH http://localhost:8080/exchangeRate/USDRU
Accept: application/json
Content-Type: application/x-www-form-urlencoded

rate=1

### Update exchange rate - 404 Not Found
### Exchange rate not found in the database
PATCH http://localhost:8080/exchangeRate/BYNRUB
Accept: application/json
Content-Type: application/x-www-form-urlencoded

rate=91.496732